### PR TITLE
some errors are fixed and some enhancements are made

### PR DESCRIPTION
**Pull request by HuzeyfeAyaz**

### CODE REVIEW

**Comment by vinid** [comment]
Thank you very much for the PR!

@silviatti and I will go through it in the next days and provide feedback / merge it

**Comment by HuzeyfeAyaz** [comment]
Hi @vinid and @silviatti, have you had a chance to look at this yet?

**Comment by vinid** [comment]
Sorry @HuzeyfeAyaz!

We will finish discussing the edits and merge the PR on Saturday

**Comment by vinid** [comment]
v2.3.0 is up :) we have also update the documentation

Thank you for this PR!

**Comment by HuzeyfeAyaz** [comment]
Great!

Thank you for merging!

**Pull request merged**
